export const paramsData = (overrides = {}) => ({
  antiRotation: '',
  antiScale: 3.585,
  builtInDeckSelector: true,
  builtInTooltip: true,
  externalPassengerManagement: false,
  hiddenSeatFeatures: [],
  innerWidth: 1434,
  isHorizontal: false,
  isTouchDevice: false,
  rightToLeft: false,
  offset: '',
  rotation: '',
  scale: 0.2789400278940028,
  scaledTotalDecksHeight: '3942.426778242678px',
  separateDeckHeights: [14133.6, 13451.6],
  singleDeckMode: true,
  tooltipOnHover: false,
  totalDecksHeight: 14133.6,
  visibleCabinTitles: true,
  visibleFuselage: true,
  visibleWings: true,
  ...overrides,
});
